<head><META http-equiv="Content-Type" content="text/html;charset=UTF-8"></head>









<html>
<head>
        <title>Ariroam</title>
        <meta http-equiv="Content-Type" content="text/html;" />
        <meta http-equiv="pragma" content="no-cache" />
        <meta http-equiv="expires" content="-1"/>
        <style>
                .mystyle1 { FONT-FAMILY:Arial;FONT-SIZE:10;}
                .text1 {  font-family: Arial; font-size: 11px}
        </style>
<script language="JavaScript" src="/javascript/cyberoamAjax.js"></script>     
<script language="JavaScript">
		var timer='';
		var liveReqTimeInJS=180;
        function openMyAccountWindow(){
                window.open("/myaccount.html",'_person')
        }
        function validateLogout(){
		}
		function validateLogin(){
				re = /\w{1,}/;
				usernamere=/^[a-zA-Z0-9_\.\@\- ]{1,60}$/;
				if (!(re.test(document.forms[0].username.value))){
					alert("Please Enter Username");
              		document.forms[0].username.focus();
             		return false; 
  				}
				else if (!(usernamere.test(document.forms[0].username.value))){
            		alert("Only alpha numeric characters are allowed in Username");
					document.forms[0].username.focus();
             		return false; 
   				} 
                if(document.forms[0].password.value==''){
                	alert("Please Enter Password");
               		document.forms[0].password.focus(); 
            		return false; 
  				}
       			document.forms[0].mode.value='191';
		}
        function checkSubmit(){
  				if(document.forms[0].btnSubmit.value == 'Login'){
 					return validateLogin();
  				}else if(document.forms[0].btnSubmit.value == 'Logout'){ 
  					validateLogout();
 				}
  		}
  		function setValues(){
  			document.httpclientloginfrm.username.value='11030142024@sicsr.edu';
			document.httpclientloginfrm.password.value='';
			document.httpclientloginfrm.saveinfo.checked='';
			
			
		}
		function showMessage(Message){
   			alert(Message);
		}
		function sendLiveRequest(){
			url='/corporate/servlet/CyberoamHTTPClient?mode=192&username=11030142024@sicsr.edu';
			invokeAjaxURL(url,"get")			
		}
		function setTimeForLiveRequest(timeInSecs){
			clearTimeout(timer);
			if(timeInSecs != -1) {
				timer=setTimeout("sendLiveRequest()",timeInSecs*1000);
			}
		}
		function parseXML(responseXML){
		   if(responseXML ==null){
		   		setTimeForLiveRequest(liveReqTimeInJS);
		   }else {
			   var  xmlDoc=responseXML.documentElement;
			   
			   var liveMessage=null;
			   try{
			   	liveMessage=xmlDoc.getElementsByTagName("livemessage")[0].childNodes[0].nodeValue;
			   }catch(e) {}
			   
			   var logoutStatus=null;
			   try{
			   logoutStatus=xmlDoc.getElementsByTagName("logoutstatus")[0].childNodes[0].nodeValue;
			   }catch(e) {}
			   
			   var loginStatus=null
			   try{
			   loginStatus=xmlDoc.getElementsByTagName("loginstatus")[0].childNodes[0].nodeValue;
			   }catch(e) {}
			   
			   var liveRequestTime=null;
			   try{
			   liveRequestTime=xmlDoc.getElementsByTagName("liverequesttime")[0].childNodes[0].nodeValue;
			   }catch(e) {}
			   
			   if(liveMessage != null){
			       showMessage(liveMessage);
			   }
			   if(logoutStatus != null || loginStatus != null){
			    	if(logoutStatus == "true" || loginStatus == "false" ){
			    			window.location.href="/corporate"+"/webpages/httpclientlogin.jsp?logoutstatus=true&message=" +liveMessage;
			    			return;
			    		}
			   }
			   if(liveRequestTime != null){
			   		liveReqTimeInJS=liveRequestTime;
			 		setTimeForLiveRequest(liveRequestTime);  
			   }else {
			   		setTimeForLiveRequest(liveReqTimeInJS);
			   }
			}
		}
		
</script>

</head>
<body  onload="setValues();document.httpclientloginfrm.username.focus();"  bgcolor="#ffffff" leftmargin="1" topmargin="0" marginwidth="0" marginheight="0" >
<form name="httpclientloginfrm" target="_parent" method="post" onSubmit="return checkSubmit();" action="/corporate/servlet/CyberoamHTTPClient">
<input type="hidden" value="191" name="mode" style="display: none;"  maxlength="3"/>
<input type="hidden" value="" name="isAccessDenied" style="display: none;"  />
<input type="hidden" value="" name="url" style="display: none;" />
<input type="hidden" name="message" style="display: none;" />
<link rel="stylesheet" href="/css/cyberoam.css" />

<!-- Dynamic jsp is included over here and this is generated by template customization -->
<head><META http-equiv="Content-Type" content="text/html;charset=UTF-8"></head><link href="/css/cyberoam.css" rel="stylesheet" /><div id="jsena"><table cellspacing="0" cellpadding="0" border="0" hight="600">    <tbody>        <tr>            <td class="uppertab" valign="top" align="left" height="590">            <table cellspacing="0" cellpadding="0" border="0">                <tbody>                    <tr>                        <td><img alt="" src="/images/cyberoamlogo.jpg" /></td>                    </tr>                    <tr>                        <td class="unselectednavtd"><nobr>&nbsp;&nbsp; <a href="javascript:openMyAccountWindow()"><font class="unselectednavfont">My Account</font> </a>&nbsp;&nbsp;</nobr></td>                    </tr>                </tbody>            </table>            </td>            <td valign="top" width="100%" height="600">            <table cellspacing="0" cellpadding="0" width="100%" border="0">                <tbody>                    <tr>                        <td>                        <table height="67" cellspacing="0" cellpadding="0" width="100%" bgcolor="#4b628e" border="0">                            <tbody>                                <tr>                                    <td style="BACKGROUND-REPEAT: repeat-y" valign="bottom" background="/images/inner_top_bkg.jpg">                                    <table cellspacing="0" cellpadding="0" width="100%" border="0">                                        <tbody>                                            <tr>                                                <td valign="bottom"><font face="arial" color="#ffffff" size="4">&nbsp;&nbsp;&nbsp;&nbsp;SICSR Http Client</font> </td>                                            </tr>                                        </tbody>                                    </table>                                    </td>                                </tr>                            </tbody>                        </table>                        </td>                    </tr>                    <tr>                        <td align="center"><br />                        <table id="LoginTable" height="100" width="222" border="0"><TR><td align="center" colspan="2"><font class="note"></font></td></TR>                            <tbody>                                <tr>                                    <td align="center" colspan="2"><font class="tableheaderfont">Client Login</font></td>                                </tr>                                <tr>                                    <td><font class="tableheaderfont">User Name</font></td>                                    <td><input maxlength="60" name="username" value='11030142024@sicsr.edu' /></td>                                </tr>                                <tr>                                    <td><font class="tableheaderfont">Password</font></td>                                    <td><input type="password" name="password" value='' autocomplete="off"/></td>                                </tr>                                <tr>                                    <td align="right"><input type="checkbox" name="saveinfo"  value="saveinfo" /></td>                                    <td><font class="tableheaderfont">Save Password</font></td>                                </tr>                                <tr>                                    <td align="center" colspan="2"><input class="buttonstyle" type="submit" name="btnSubmit" value="Login" /> </td>                                </tr><TR><td align="center" colspan="2"><font class="note"></font></td></TR>                            </tbody>                        </table>                        <br /></td>                    </tr>                </tbody>            </table>            </td>        </tr>    </tbody></table></div></form></body></html>

<!-- Dynamic jsp process ends here -->

</form>
</body>
</html>        	                           
