<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" href="styles/layout.css" type="text/css" />
<title>Untitled Document</title>
<style type="text/css">
<!--
.style1 {font-size: 18px}
-->
</style>
</head>
<body background="images/background-001.jpg">
<div class="div_main">

	<div class="div_header">
	
		<div class="div_header_top">
		  <strong class="font_strong">Welcome <a href="#" class="link_regular"> Guest </a>&nbsp;
		 (&nbsp;<a href="#" class="link_regular">Login</a>&nbsp;)&nbsp;</strong>
		</div>
		
		<div class="div_header_middle">
			<img src="images/sicsr-head.jpg" class="img_header"/>
		</div>
		
		<div class="div_header_bottom">
		  <form action="#" method="post" id="sitesearch">	
          	<strong class="font_strong">Search&nbsp;&nbsp;</strong>
          	<input type="text" value="Search In Website" size="30" />
          	<input name="image" type="image" class="search_button" id="search" src="images/magnifying_glass.png" alt="Search" />
          	&nbsp;&nbsp; &nbsp; 
	      </form>
		</div>
	</div>
	
	<div class="div_menu">
		<table class="menu_table">
		<tr>
		<td><a class="link_menu" href="#">Home</a></td>
		<td><a class="link_menu" href="#">Programmes</a></td>
		<td><a class="link_menu" href="#">Faculty</a></td>
		<td><a class="link_menu" href="#">PhotoGallery</a></td>
		<td><a class="link_menu" href="#">Placement</a></td>
		<td><a class="link_menu" href="#">Events</a></td>
		<td><a class="link_menu" href="#">ContactUS</a></td>						
		</tr>
		</table>
	</div>
	
	<div class="div_middle">
		<div class="div_middle_left">
		<form id="profile_display">
		<table class="menu_left">
			<tr class="menu_left_row_students"><td><img src="images/profile_pic.jpg" class="profile_pic" /></td></tr>
			<tr class="menu_left_row_students">
					  <td class="profile_text">Name: <input name="text" type="text" value="&lt;&lt; Full Name &gt;&gt;" size="14" readonly="true" /></td>
			</tr>
			<tr class="menu_left_row_students">
				<td class="link_profile_edit"><a href="#" class="link_edit">edit</a>&nbsp;&nbsp;</td>
			</tr>
			<tr class="menu_left_row_students"><td><hr class="line_left_menu"/></td></tr>
			<tr class="menu_left_row_students">
					<td class="profile_text">
					<select class="drop_down">
						<option value="||value_here||">MSc(ca) 2011-2013</option>
					</select>
					</td>
			</tr>
			
			<tr class="menu_left_row_students"><td><hr class="line_left_menu"/></td></tr>
			<tr class="menu_left_row_students"><td><a href="#" class="link_menu_left">Attendence</a></td></tr>
			<tr class="menu_left_row_students"><td><hr class="line_left_menu"/></td></tr>
			<tr class="menu_left_row_students"><td><a href="#" class="link_menu_left">Notes</a></td></tr>
			<tr class="menu_left_row_students"><td><hr class="line_left_menu"/></td></tr>
			<tr class="menu_left_row_students"><td><a href="#" class="link_menu_left">Resources</a></td></tr>
			<tr class="menu_left_row_students"><td><hr class="line_left_menu"/></td></tr>
			<tr class="menu_left_row_students"><td><a href="#" class="link_menu_left">Assignments</a></td></tr>
			<tr class="menu_left_row_students"><td><hr class="line_left_menu"/></td></tr>
			<tr class="menu_left_row_students"><td><a href="#" class="link_menu_left">Posts</a></td></tr>
			<tr class="menu_left_row_students"><td><hr class="line_left_menu"/></td></tr>
			<tr class="menu_left_row_students"><td><a href="#" class="link_menu_left">Time Table</a></td></tr>
			<tr class="menu_left_row_students"><td><hr class="line_left_menu"/></td></tr>
			<tr class="menu_left_row_students"><td><a href="#" class="link_menu_left">Results</a></td></tr>
		</table>
		</form>
		</div>
		
		<div class="div_middle_right">
		